/*******************************************************/
/**  Autogenerated lts rules (regex) for cmu     */
/**  from wfst/    */
/*******************************************************/

#include "cst_string.h"
#include "cst_lts.h"
#include "cst_lexicon.h"

const char * const cmu_lts_phone_table[76] = 
{
    "epsilon",
    "eh1",
    "aa1",
    "ey1",
    "aw1",
    "ax0",
    "ao1",
    "er0",
    "ay0",
    "aa0",
    "ey0",
    "ih1",
    "ae1",
    "aw0",
    "ow0",
    "ao0",
    "ow1",
    "eh0",
    "iy1",
    "ih0",
    "w-ey1",
    "w-ax0",
    "y-ax0",
    "ae0",
    "ay1",
    "ah0",
    "ah1",
    "b",
    "ch",
    "k",
    "s",
    "sh",
    "t-s",
    "d",
    "t",
    "jh",
    "iy0",
    "uw1",
    "y-uw1",
    "oy1",
    "uw0",
    "y-uw0",
    "oy0",
    "f",
    "g",
    "zh",
    "hh",
    "y",
    "l",
    "ax0-l",
    "m",
    "ax0-m",
    "m-ae1",
    "m-ax0",
    "ng",
    "n",
    "n-y",
    "uh1",
    "uh0",
    "w",
    "w-ah1",
    "er1",
    "p",
    "r",
    "z",
    "th",
    "dh",
    "y-uh1",
    "y-er1",
    "y-er0",
    "v",
    "k-s",
    "g-zh",
    "k-sh",
    "g-z",
    NULL
};

const char * const cmu_lts_letter_table[30] = 
{
    "nothing",
    "#",
    "0",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    NULL
};

const cst_lts_addr cmu_lts_letter_index[27] = 
{
    0, /* a */
    5436, /* b */
    5489, /* c */
    6103, /* d */
    6203, /* e */
    11189, /* f */
    11275, /* g */
    11754, /* h */
    11990, /* i */
    15857, /* j */
    15968, /* k */
    15981, /* l */
    16467, /* m */
    16583, /* n */
    16942, /* o */
    20591, /* p */
    20724, /* q */
    20725, /* r */
    22497, /* s */
    23452, /* t */
    24119, /* u */
    25967, /* v */
    25977, /* w */
    26134, /* x */
    26176, /* y */
    26618, /* z */
    0
};

